default_environment: development
enable_caching: true
enable_connection_pooling: false
max_connections_per_credential: 5
strict_environment_isolation: true

environments:
  development:
    name: development
    default_credential:
      method: application_default

  staging:
    name: staging
    default_credential:
      method: application_default

  production:
    name: production
    default_credential:
      method: application_default
